services:
  vite-app:
    build: .
    ports:
      - "3000:3000"
    container_name: vite-container
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development